version: '3.6'
services:

  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        POETRY_INSTALL_EXTRA_ARGS: ""
        UID: "${UID}"
        GID: "${UID}"
    container_name: smart-calculator
    volumes:
      - ./:/code
